global:
  scrape_interval: 15s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'pcontainer'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8090']      
  - job_name: 'demoapp'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8082']          
  
